plugins {
    id 'java-library'
}

base {
    archivesName = 'minis-bot-mod'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        minisbot {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : "minis-bot-mod",
                "Specification-Vendor"    : "minis",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "minis",
        ])
    }
}
