plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.174'
}

base {
    archivesName = "minis-bot-mod"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.112"
    runs {
        server { server() }
    }
    mods {
        minisbot {
            sourceSet sourceSets.main
        }
    }
}
